<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423133116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, username VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL, password VARCHAR(255) DEFAULT NULL, profile_image TEXT DEFAULT NULL, total_count_episodes_watched INT DEFAULT 0 NOT NULL, total_count_series_watched INT DEFAULT 0 NOT NULL, google_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9D17F50A6 ON "users" (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON "users" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E976F5C865 ON users (google_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C75 ON users (email)');
        $this->addSql('CREATE TABLE series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, portrait_url TEXT DEFAULT NULL, airing_status VARCHAR(20) DEFAULT NULL, total_episodes INT DEFAULT 0 NOT NULL, current_airing_episode INT DEFAULT 0 NOT NULL, airing_day VARCHAR(10) DEFAULT NULL, anilist_id INT DEFAULT 0 NOT NULL, format VARCHAR(15) NOT NULL, source VARCHAR(20) NOT NULL, season VARCHAR(25) DEFAULT NULL, english_name VARCHAR(255) DEFAULT NULL, romaji_name VARCHAR(255) NOT NULL, last_refreshed_at TIMESTAMP NULL, season_year INT DEFAULT 0 NOT NULL, genres JSON DEFAULT NULL, next_airing_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, synonyms JSONB DEFAULT \'[]\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A10012DD17F50A6 ON series (uuid)');
        $this->addSql("CREATE INDEX series_synonyms_gin ON series USING GIN (synonyms jsonb_path_ops)");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A10012D26682F6B ON series (anilist_id)');
        $this->addSql('CREATE TABLE user_series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, series_id INT NOT NULL, is_favourite BOOLEAN NOT NULL, last_episode_watched_count INT DEFAULT 0 NOT NULL,count_episodes_completed INT DEFAULT 0 NOT NULL, is_completed BOOLEAN DEFAULT FALSE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F421A10D17F50A6 ON user_series (uuid)');
        $this->addSql('CREATE INDEX IDX_5F421A10A76ED395 ON user_series (user_id)');
        $this->addSql('CREATE INDEX IDX_5F421A105278319C ON user_series (series_id)');
        $this->addSql('ALTER TABLE user_series ADD CONSTRAINT FK_5F421A10A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_series ADD CONSTRAINT FK_5F421A105278319C FOREIGN KEY (series_id) REFERENCES series (id) NOT DEFERRABLE');
        $this->addSql('CREATE TABLE user_episode_watch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, series_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_858F1122D17F50A6 ON user_episode_watch (uuid)');
        $this->addSql('CREATE INDEX IDX_858F1122A76ED395 ON user_episode_watch (user_id)');
        $this->addSql('CREATE INDEX IDX_858F11225278319C ON user_episode_watch (series_id)');
        $this->addSql('ALTER TABLE user_episode_watch ADD CONSTRAINT FK_858F1122A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_episode_watch ADD CONSTRAINT FK_858F11225278319C FOREIGN KEY (series_id) REFERENCES series (id) NOT DEFERRABLE');
        $this->addSql('CREATE EXTENSION IF NOT EXISTS pg_trgm');
        $this->addSql('CREATE INDEX series_romaji_trgm ON series USING GIN (LOWER(romaji_name) gin_trgm_ops)');
        $this->addSql("CREATE INDEX series_english_trgm ON series USING GIN (LOWER(COALESCE(english_name, '')) gin_trgm_ops)");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE series DROP CONSTRAINT FK_3A10012DA76ED395');
        $this->addSql('DROP INDEX UNIQ_3A10012D26682F6B');
        $this->addSql('ALTER TABLE user_series DROP CONSTRAINT FK_5F421A10A76ED395');
        $this->addSql('ALTER TABLE user_series DROP CONSTRAINT FK_5F421A105278319C');
        $this->addSql('DROP INDEX UNIQ_1483A5E9E7927C74');
        $this->addSql('DROP INDEX UNIQ_1483A5E976F5C865');
        $this->addSql('ALTER TABLE user_episode_watch DROP CONSTRAINT FK_858F1122A76ED395');
        $this->addSql('ALTER TABLE user_episode_watch DROP CONSTRAINT FK_858F11225278319C');
        $this->addSql('DROP TABLE user_episode_watch');
        $this->addSql('DROP TABLE user_series');
        $this->addSql('DROP TABLE "users"');
        $this->addSql('DROP TABLE series');
    }
}
